
import type { RawJsonlEntry, DistilledMessage } from '@/shared/types.js';

export type { RawJsonlEntry, DistilledKind, DistilledMessage } from '@/shared/types.js';

interface Block { type?: string; text?: string; name?: string }

function toBlocks(content: unknown): Block[] {
  if (Array.isArray(content)) return content as Block[];
  return [];
}

function userText(content: unknown): string | null {
  if (typeof content === 'string') return content.trim() || null;
  const blocks = toBlocks(content);
  const text = blocks.filter((b) => b.type === 'text' && typeof b.text === 'string').map((b) => b.text).join('\n');
  if (text.trim()) return text.trim();
  return null;
}

function isToolResultOnly(content: unknown): boolean {
  const blocks = toBlocks(content);
  return blocks.length > 0 && blocks.every((b) => b.type === 'tool_result');
}

// Claude Code harness-injected "user" turns that the HUMAN never typed — slash
// command expansions, local-command stdout/caveats, skill content dumps, the
// auto continuation, interrupt markers, system reminders. They carry role:user
// in the jsonl, so without this filter they show up as phantom user bubbles in
// the IM chat (and the skill dumps are huge — they also cause the typing lag).
// Matched by prefix on the trimmed text; these markers are unambiguous.
const SYNTHETIC_USER_PREFIXES = [
  '[Request interrupted by user',
  '<command-name>',
  '<command-message>',
  '<command-args>',
  '<local-command-stdout>',
  '<local-command-stderr>',
  '<local-command-caveat>',
  '<system-reminder>',
  '<user-prompt-submit-hook>',
  'Caveat: The messages below were generated by the user while running local commands',
  'Continue from where you left off',
  'Base directory for this skill:',
];

function isSyntheticUserTurn(text: string): boolean {
  const t = text.trimStart();
  return SYNTHETIC_USER_PREFIXES.some((p) => t.startsWith(p));
}

/**
 * True iff this entry is a user *text* message — i.e. the kind of entry that
 * `distillJsonl` treats as a turn boundary (it flushes the prior assistant
 * turn). Tool-result-only user entries are NOT boundaries. Used by the
 * incremental ingest to find a safe rewind point: everything before the last
 * such entry is a finalized, immutable turn.
 */
export function isUserTextEntry(entry: RawJsonlEntry): boolean {
  return (
    entry.type === 'user' &&
    !isToolResultOnly(entry.message?.content) &&
    userText(entry.message?.content) !== null
  );
}

function ts(entry: RawJsonlEntry): number {
  const t = entry.timestamp ? Date.parse(entry.timestamp) : NaN;
  return Number.isFinite(t) ? t : 0;
}

/**
 * Distill raw Claude Code jsonl entries into a clean IM message stream.
 * Pure & deterministic — no IO, safe to unit test.
 */
export function distillJsonl(entries: RawJsonlEntry[]): DistilledMessage[] {
  const out: DistilledMessage[] = [];

  let accText = '';
  let toolCount = 0;
  let rawStart: string | null = null;
  let rawEnd: string | null = null;
  let firstAssistantId: string | null = null;
  let lastAssistantId: string | null = null;
  let lastAssistantTs = 0;
  let turnIsError = false;

  const flushAssistant = () => {
    if (lastAssistantId === null && toolCount === 0) return;
    if (!accText.trim() && toolCount === 0) return;
    // Key the result on the turn's FIRST assistant entry — this id is stable as
    // the turn streams in (later entries append text), so re-ingesting a growing
    // jsonl UPSERTs the same row instead of orphaning a stale partial bubble.
    const sourceId = firstAssistantId ?? rawStart ?? `turn-${out.length}`;
    // A tools-only turn (no concluding text) legitimately yields content: '' and is still emitted so the toolTrace stays visible to the UI.
    const msg: DistilledMessage = {
      sourceId,
      role: 'assistant',
      kind: turnIsError ? 'error' : 'result',
      content: accText.trim(),
      createdAt: lastAssistantTs,
    };
    if (toolCount > 0 && rawStart && rawEnd) {
      msg.toolTrace = { count: toolCount, rawRefStart: rawStart, rawRefEnd: rawEnd };
    }
    out.push(msg);
    accText = '';
    toolCount = 0;
    rawStart = null;
    rawEnd = null;
    firstAssistantId = null;
    lastAssistantId = null;
    lastAssistantTs = 0;
    turnIsError = false;
  };

  const noteRaw = (id?: string) => {
    if (!id) return;
    if (rawStart === null) rawStart = id;
    rawEnd = id;
  };

  for (const entry of entries) {
    if (entry.type === 'user') {
      if (isToolResultOnly(entry.message?.content)) {
        // Extends the rawRef range for the "view full record" viewer but does NOT
        // increment toolCount — only tool_use blocks in assistant entries count.
        noteRaw(entry.uuid);
        continue;
      }
      const text = userText(entry.message?.content);
      if (text) {
        // Still a turn boundary (flush the prior assistant), but DON'T surface
        // harness-injected turns as human user bubbles.
        flushAssistant();
        if (!isSyntheticUserTurn(text)) {
          out.push({
            sourceId: entry.uuid ?? `user-${out.length}`,
            role: 'user',
            kind: 'text',
            content: text,
            createdAt: ts(entry),
          });
        }
      }
      continue;
    }

    if (entry.type === 'assistant') {
      const blocks = toBlocks(entry.message?.content);
      if (typeof entry.message?.content === 'string') {
        accText += entry.message.content;
      }
      let hasToolUse = false;
      for (const b of blocks) {
        if (b.type === 'text' && typeof b.text === 'string') accText += b.text;
        else if (b.type === 'tool_use') { toolCount += 1; hasToolUse = true; }
      }
      // Only extend rawRef range for entries that contain tool_use blocks
      if (hasToolUse) noteRaw(entry.uuid);
      if (firstAssistantId === null) firstAssistantId = entry.uuid ?? null;
      lastAssistantId = entry.uuid ?? lastAssistantId;
      lastAssistantTs = ts(entry);
      if (entry.isError) turnIsError = true;
      continue;
    }
  }

  flushAssistant();
  return out;
}
